baseURL = '/'
languageCode = 'en-us'
title = "Causal Deference"
theme = 'etch'
features = ["responsive", "google analytics"]

[outputs]
    section = ['html', 'rss']

[params]
    [params.author]
        name = "John McDonnell"
        email = "john.v.mcdonnell+hugoblog@gmail.com"
        homepage = "https://jvmcdonnell.com"
        github = "https://github.com/johnmcdonnell"
        twitter = "https://twitter.com/johnvmcdonnell"
    
    mainSections = ["posts"]
    intro = true
    opengraph = true
    shareTwitter = true
    dateFormat = "Jan 2, 2006"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20


[Permalinks]
    post = "/:filename/"

