baseURL = '/'
languageCode = 'en-us'
title = "Causal Deference"
theme = 'etch'
features = ["disqus", "responsive", "google analytics"]

[Params]
    mainSections = ["posts"]
    intro = true
    github = "https://github.com/johnmcdonnell"
    twitter = "https://twitter.com/johnvmcdonnell"
    email = "john.v.mcdonnell@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Jan 2, 2006"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20



[author]
    name = "John McDonnell"
    homepage = "https://jvmcdonnell.com"
    github = "https://github.com/johnmcdonnell"
    twitter = "https://twitter.com/johnvmcdonnell"

[Permalinks]
    post = "/:filename/"

